defaults:
  cuda_id: "0"
  dataset: "WebNLG"
  rounds: 4
  train: "train"
  batch_size: 6
  test_batch_size: 6
  learning_rate: 3e-5
  num_train_epochs: 50
  fix_bert_embeddings: false
  bert_vocab_path: "./pretrained/bert-base-cased/vocab.txt"
  bert_config_path: "./pretrained/bert-base-cased/config.json"
  bert_model_path: "./pretrained/bert-base-cased/pytorch_model.bin"
  max_len: 100
  warmup: 0.0
  weight_decay: 0.0
  max_grad_norm: 1.0
  min_num: 1e-7
  base_path: "./dataset"
  output_path: "./ckpt"
  save_interval: 1
  seed: 0
  eval_mode: "test"
  test_groundtruth_ratio: 0.45

label_list:
  - "N/A"
  - "SMH"
  - "SMT"
  - "SS"
  - "MMH"
  - "MMT"
  - "MSH"
  - "MST"

logging:
  level: "INFO"
  sample_log: true
  sample_text_max_len: 200
  sample_triple_max_len: 200
  sample_log_template: |-
    测试样本 {index}/{total}
    输入={text}
    正确答案={gold}
    模型预测={pred}
